version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend-container
    ports: 
      - "3000:3000"

  frontend:
    build: ./frontend
    container_name: frontend-container
    ports:
      - "3001:3001"

